name: Deploy Function

on:
  workflow_run:
    branches: [main]
    workflows: ["CI"]
    types:
      - completed
  workflow_dispatch:

jobs:
  deploy-commands:
    runs-on: ubuntu-latest

    env:
      DISCORD_PUBLIC_KEY: ${{  secrets.DISCORD_PUBLIC_KEY }}
      DISCORD_BOT_TOKEN: ${{  secrets.DISCORD_BOT_TOKEN }}
      DISCORD_APP_ID: ${{  secrets.DISCORD_APP_ID }}

    steps:
      - uses: actions/checkout@v4
      - uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x
      - run: deno task deploy-bot-commands

  deploy-to-supabase:
    runs-on: ubuntu-latest

    env:
      SUPABASE_ACCESS_TOKEN: ${{  secrets.SUPABASE_ACCESS_TOKEN }}
      PROJECT_ID: ${{  secrets.SUPABASE_PROJECT_ID }}

    steps:
      - uses: actions/checkout@v4

      - uses: supabase/setup-cli@v1
        with:
          version: latest

      - run: supabase functions deploy dusktools --project-ref $PROJECT_ID --no-verify-jwt
      - run: supabase functions deploy sync-campaign-with-discord --project-ref $PROJECT_ID
      - run: supabase functions deploy send-message-to-notification-channel --project-ref $PROJECT_ID
      - run: supabase functions deploy update-deferred-discord-message --project-ref $PROJECT_ID
